### ISSUE TITLE
Missing remoteSyslog property

### ISSUE THREAD

**Issue by eeldivad** [bottkars/SIORestToolkit#2]
I'm trying to get the remoteSyslog information but I don't see it in any of the functions.

I found this post which someone posted remoteSyslog is output from connect-siogateway function, but when I do it the property doesn't exist.  I even did a get-member to see all possible properties.  I'm using the latest SIORestToolKit 2.0.1.4000

Here's the post where it appears remoteSyslog is returned from connect-siogateway
https://github.com/thecodeteam/SIOToolKit/issues/4

Here's the output I get

d:\scripts> Connect-SIOgateway x.x.x.x -Credentials $cred -trustCert
Successfully connected to ScaleIO https://x.x.x.x:443

systemId                    : 5aeb4950605e91c6
mdmPort                     : 6611
snmpResendFrequency         : 0
snmpSamplingFrequency       : 30
featuresEnableSnmp          : true
cipherSuites                :
featuresEnableIM            : true
snmpPort                    : 162
bypassCertificateCheck      : false
mdmUsername                 : admin
mdmAddresses                : {x.x.x.x, x.x.x.x}
snmpTrapsReceiverIps        : {x.x.x.x}
allowNonSecureCommunication : false

**Comment by eeldivad** [comment]
Anyone have any ideas?

**Comment by bottkars** [comment]
hi,
is this a free and frictionless install or a fully licensed SIO Install ?

**Comment by eeldivad** [comment]
You are right.  The free version doesn't have remoteSyslog property.  Thanks!
